
name: Generate Snake
permissions: 
  contents: write

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Biswajitsahoo897
          outputs: dist/github-snake.svg
          # Add these lines for black background
          svg_color_bg: "000000"  # Black background
          svg_color_border: "000000"  # Black border (optional)
          svg_color_snake: "00FF00"  # You can change snake color too if you want
          
      - run: git status
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
          
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
