name: Generate Snake with Black Background
on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:        # Allows manual triggering

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake (Black Background)
        uses: Platane/snk@v3
        with:
          github_user_name: Biswajitsahoo897  # Replace with your GitHub username
          outputs: |
            dist/snake.svg?color_bg=000000&color_snake=00FF00&color_border=000000
            dist/snake-dark.svg?palette=github-dark  # Alternative dark theme
          
      - name: Upload to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages  # Or "output" if you prefer
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
