name: Generate Snake
permissions: 
  contents: write

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Biswajitsahoo897
          outputs: dist/github-snake.svg
          # Set colors for black background and a colored snake
          color_snake: '#00FF00'        # Neon green snake, or choose as you like
          color_dots: '#000000,#333333,#666666,#999999,#CCCCCC'  # gradient of dark dots
          # Note: Currently Platane/snk does not provide a direct background color option,
          # but you can achieve black-like background by tweaking color_dots to be dark
          
      - run: git status
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
          
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
